### ISSUE TITLE
plugin is broken after update

### ISSUE THREAD

**Issue by Victorbry99** [HOZHENWAI/Beets-Plugin_VGMdb#13]
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/ui/__init__.py", line 1304, in main
    _raw_main(args)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/ui/__init__.py", line 1291, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/ui/commands.py", line 1034, in import_func
    import_files(lib, paths, query)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/ui/commands.py", line 974, in import_files
    session.run()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/util/pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/util/pipeline.py", line 311, in run
    out = self.coro.send(msg)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/util/pipeline.py", line 193, in coro
    func(*(args + (task,)))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/importer.py", line 1376, in lookup_candidates
    task.lookup_candidates()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/importer.py", line 660, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/autotag/match.py", line 461, in tag_album
    for matched_candidate in hooks.album_candidates(items,
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/plugins.py", line 573, in decorated
    for v in generator(*args, **kwargs):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/autotag/hooks.py", line 632, in album_candidates
    yield from plugins.candidates(items, artist, album, va_likely, extra_tags)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/plugins.py", line 384, in candidates
    yield from plugin.candidates(items, artist, album, va_likely,
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 320, in candidates
    albums += self._search_vgmdbinfo(query)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 142, in _search_vgmdbinfo
    albums.append(self.album_for_id(album_id))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 344, in album_for_id
    return self.format_album_vgmdbinfo(vgmdbinfo, url=url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 222, in format_album_vgmdbinfo
    tracks = self._format_track_info(albuminfo, url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 169, in _format_track_info
    track_title = track["names"][lang]
KeyError: 'Romaji'
```

**Comment by Victorbry99** [comment]
it happens with every album, here's another album log:
```
VGMplug: Querying VgmDB for release 121535
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/ui/__init__.py", line 1304, in main
    _raw_main(args)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/ui/__init__.py", line 1291, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/ui/commands.py", line 1034, in import_func
    import_files(lib, paths, query)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/ui/commands.py", line 974, in import_files
    session.run()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/util/pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/util/pipeline.py", line 311, in run
    out = self.coro.send(msg)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/util/pipeline.py", line 193, in coro
    func(*(args + (task,)))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/importer.py", line 1376, in lookup_candidates
    task.lookup_candidates()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/importer.py", line 660, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/autotag/match.py", line 461, in tag_album
    for matched_candidate in hooks.album_candidates(items,
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/plugins.py", line 573, in decorated
    for v in generator(*args, **kwargs):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/autotag/hooks.py", line 632, in album_candidates
    yield from plugins.candidates(items, artist, album, va_likely, extra_tags)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beets/plugins.py", line 384, in candidates
    yield from plugin.candidates(items, artist, album, va_likely,
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 320, in candidates
    albums += self._search_vgmdbinfo(query)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 142, in _search_vgmdbinfo
    albums.append(self.album_for_id(album_id))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 344, in album_for_id
    return self.format_album_vgmdbinfo(vgmdbinfo, url=url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 222, in format_album_vgmdbinfo
    tracks = self._format_track_info(albuminfo, url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/beetsplug/VGMplug.py", line 169, in _format_track_info
    track_title = track["names"][lang]
KeyError: 'English'
```

**Comment by HOZHENWAI** [comment]
@Victorbry99
my bad, solved

**Comment by HOZHENWAI** [comment]
i created another issue when solving this one, it ignores the lang preference order...

**Comment by HOZHENWAI** [comment]
@Victorbry99 it should be good with v1.2.3
